### model
model_name_or_path: deepseek-ai/deepseek-math-7b-base

### method
stage: vm
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: alphamath
template: vanilla
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/alphamath-7b/lora/vm
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 14
gradient_accumulation_steps: 10
learning_rate: 4.0e-5
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
